[build-system]
requires = ["setuptools", "wheel", "pybind11", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "linear_training_mk_demo"
version = "0.0.1"
description = "Linear training megakernel demo."
requires-python = ">=3.10"
